// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBThCwjMIFFK3-6wUaIRvpR4-nh6O6aCtc',
    appId: '1:872160576746:web:27217bf1018e3ebd5d4393',
    messagingSenderId: '872160576746',
    projectId: 'appdeliverymoto',
    authDomain: 'appdeliverymoto.firebaseapp.com',
    storageBucket: 'appdeliverymoto.firebasestorage.app',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCYZblr3hNoyUDdEc-gWkmBgLP8GuwOQZ0',
    appId: '1:872160576746:android:418b65411ee385dc5d4393',
    messagingSenderId: '872160576746',
    projectId: 'appdeliverymoto',
    storageBucket: 'appdeliverymoto.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAJCOYVfF00az8UZ9fguGyERwGOVW3DEso',
    appId: '1:872160576746:ios:6f882416fe1b98645d4393',
    messagingSenderId: '872160576746',
    projectId: 'appdeliverymoto',
    storageBucket: 'appdeliverymoto.firebasestorage.app',
    iosBundleId: 'com.example.appdeliverymoto',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAJCOYVfF00az8UZ9fguGyERwGOVW3DEso',
    appId: '1:872160576746:ios:6f882416fe1b98645d4393',
    messagingSenderId: '872160576746',
    projectId: 'appdeliverymoto',
    storageBucket: 'appdeliverymoto.firebasestorage.app',
    iosBundleId: 'com.example.appdeliverymoto',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBThCwjMIFFK3-6wUaIRvpR4-nh6O6aCtc',
    appId: '1:872160576746:web:ed9c7d336e4ccff25d4393',
    messagingSenderId: '872160576746',
    projectId: 'appdeliverymoto',
    authDomain: 'appdeliverymoto.firebaseapp.com',
    storageBucket: 'appdeliverymoto.firebasestorage.app',
  );
}
